import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowUpRight, Bell, BookOpen, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, FileText, LayoutDashboard, Menu, MessageSquareText, RefreshCw, Search, ShieldCheck, Sparkles, UploadCloud, X } from 'lucide-react'
import { api, demoApprovals, demoProfile } from './api'
import { demoSchemes } from './data'

const labels = { not_started: 'Not started', in_progress: 'In progress', submitted: 'Submitted', approved: 'Approved' }
const initialProfile = { name: '', industry_category: 'food_processing', location_district: 'Pune', investment_amount: 6000000, project_stage: 'new_setup', employee_count: 18 }

function App() {
  const [view, setView] = useState('overview')
  const [role, setRole] = useState('entrepreneur')
  const [profile, setProfile] = useState(null)
  const [profileForm, setProfileForm] = useState(initialProfile)
  const [approvals, setApprovals] = useState([])
  const [schemes, setSchemes] = useState([])
  const [schemeFilter, setSchemeFilter] = useState('all')
  const [profileMatches, setProfileMatches] = useState([])
  const [alerts, setAlerts] = useState([{ id: 1, title: 'Your profile is ready for review', text: 'Complete your approval checklist to continue.', read: false }])
  const [toast, setToast] = useState('')
  const [online, setOnline] = useState(true)
  const [mobileNav, setMobileNav] = useState(false)

  useEffect(() => { loadSchemes() }, [])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer) }, [toast])

  async function loadSchemes() {
    try { const result = await api.schemes(); setSchemes(result.items); setOnline(true) } catch { setSchemes(demoSchemes); setOnline(false) }
  }

  async function createProfile(event) {
    event.preventDefault()
    try {
      const created = await api.createProfile({ ...profileForm, investment_amount: Number(profileForm.investment_amount), employee_count: Number(profileForm.employee_count) })
      setProfile(created); await loadChecklist(created.id); setToast('Profile saved and checklist generated')
    } catch {
      setProfile({ ...demoProfile, ...profileForm }); setApprovals(demoApprovals); setProfileMatches([]); setToast('Demo profile loaded. Connect Supabase to persist it.')
    }
    setView('checklist')
  }

  async function loadChecklist(id) {
    try { const result = await api.checklist(id); setApprovals(result.approvals) } catch { setApprovals(demoApprovals) }
    try { const result = await api.profileSchemes(id); setProfileMatches(result.matches) } catch { setProfileMatches([]) }
  }

  function selectView(next) { setView(next); setMobileNav(false) }
  const progress = approvals.length ? Math.round((approvals.filter(item => item.status === 'approved').length / approvals.length) * 100) : 0
  const filteredSchemes = schemes.filter(item => schemeFilter === 'all' || item.government_level === schemeFilter)

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark">M</div><div><strong>MAHA<span>FLOW</span></strong><small>Approval intelligence</small></div></div>
      <div className="role-switch"><button className={role === 'entrepreneur' ? 'active' : ''} onClick={() => { setRole('entrepreneur'); selectView('overview') }}>Entrepreneur</button><button className={role === 'official' ? 'active' : ''} onClick={() => { setRole('official'); selectView('official') }}>Official</button></div>
      <nav>
        {(role === 'entrepreneur' ? [
          ['overview', LayoutDashboard, 'Overview'], ['intake', MessageSquareText, 'AI intake'], ['checklist', ClipboardCheck, 'My approvals'], ['documents', FileCheck2, 'Documents'], ['schemes', BookOpen, 'Schemes'],
        ] : [['official', Activity, 'Command centre'], ['schemes', BookOpen, 'Scheme directory']]).map(([id, Icon, text]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => selectView(id)}><Icon size={17} /><span>{text}</span>{id === 'documents' && <em>2</em>}</button>)}
      </nav>
      <div className="sidebar-bottom"><div className="live-status"><span className="pulse" /> System operational</div><div className="user-chip"><div className="avatar">PD</div><div><strong>Priya Deshmukh</strong><small>Entrepreneur account</small></div><ChevronRight size={15} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileNav(!mobileNav)}><Menu size={20} /></button><div className="crumb"><span>Workspace</span><ChevronRight size={15} /><strong>{role === 'official' ? 'Command centre' : 'My approvals'}</strong></div><div className="top-actions"><div className="connection"><span className={online ? 'status-dot' : 'status-dot amber'} />{online ? 'Connected' : 'Demo mode'}</div><button className="icon-button notification"><Bell size={18} /><i>2</i></button><div className="avatar">PD</div></div></header>
      <div className="page-wrap">
        {role === 'official' ? <OfficialView schemes={schemes} onOpenSchemes={() => selectView('schemes')} /> : <>
          {view === 'overview' && <Overview profile={profile} approvals={approvals} progress={progress} selectView={selectView} alerts={alerts} />}
          {view === 'intake' && <Intake profile={profile} profileForm={profileForm} setProfileForm={setProfileForm} onSubmit={createProfile} />}
          {view === 'checklist' && <Checklist profile={profile} approvals={approvals} selectView={selectView} onRefresh={() => profile ? loadChecklist(profile.id) : setView('intake')} />}
          {view === 'documents' && <Documents setToast={setToast} profile={profile} />}
          {view === 'schemes' && <Schemes schemes={filteredSchemes} filter={schemeFilter} setFilter={setSchemeFilter} matches={profileMatches} />}
        </>}
      </div>
    </main>
    {toast && <div className="toast"><CheckCircle2 size={18} />{toast}<button onClick={() => setToast('')}><X size={15} /></button></div>}
  </div>
}

function PageTitle({ eyebrow, title, text, action }) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{text && <p>{text}</p>}</div>{action}</div> }
function Overview({ profile, approvals, progress, selectView, alerts }) { return <><PageTitle eyebrow="Thursday · 10 September 2026" title="Good morning, Priya" text="A clear path through Maharashtra's approval landscape." action={<button className="primary-button" onClick={() => selectView(profile ? 'checklist' : 'intake')}><Sparkles size={16} />{profile ? 'Continue journey' : 'Start profile'}</button>} /><section className="hero-band"><div><span className="hero-kicker"><span className="pulse" /> APPLICATION JOURNEY</span><h2>{profile?.name || 'Your next chapter starts here.'}</h2><p>{profile ? 'Your personalised approval map is ready. Keep moving with confidence.' : 'Tell us about your business and we will map the approvals, documents, and next steps.'}</p></div><div className="hero-progress"><strong>{progress}%</strong><span>journey complete</span><div className="progress-track"><i style={{ width: `${Math.max(progress, profile ? 12 : 0)}%` }} /></div></div></section><div className="stats-grid"><Stat label="Approvals mapped" value={approvals.length || '—'} detail={approvals.length ? 'For your business' : 'Start your profile'} icon={ClipboardCheck} /><Stat label="Documents ready" value="0 / 8" detail="2 need attention" icon={FileCheck2} /><Stat label="Time saved" value="4.5h" detail="Estimated this week" icon={RefreshCw} /></div><div className="content-grid"><section className="panel next-panel"><div className="panel-heading"><div><span className="eyebrow">NEXT UP</span><h3>Your approval runway</h3></div><button className="text-button" onClick={() => selectView('checklist')}>View all <ArrowUpRight size={15} /></button></div>{(approvals.length ? approvals : demoApprovals).slice(0, 3).map((item, index) => <ApprovalRow key={item.approval_id} item={item} index={index} />)}</section><section className="panel alerts-panel"><div className="panel-heading"><div><span className="eyebrow">ATTENTION</span><h3>Recent alerts</h3></div><Bell size={18} /></div>{alerts.map(alert => <div className="alert-row" key={alert.id}><div className="alert-icon"><Bell size={15} /></div><div><strong>{alert.title}</strong><p>{alert.text}</p><small>Just now</small></div></div>)}<div className="mini-note"><ShieldCheck size={16} /><span>Your data is protected and only shared with authorised departments.</span></div></section></div></> }
function Stat({ label, value, detail, icon: Icon }) { return <div className="stat-card"><div className="stat-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function ApprovalRow({ item, index }) { const status = item.status || (index === 0 ? 'in_progress' : 'not_started'); return <div className="approval-row"><div className={`step-number ${status}`}>{status === 'approved' ? <CheckCircle2 size={16} /> : index + 1}</div><div className="approval-info"><strong>{item.name}</strong><span>{item.department}</span></div><div className="approval-meta"><b className={`status ${status}`}>{labels[status] || labels.not_started}</b><small>{item.sla_days} day SLA</small></div><ChevronRight size={16} /></div> }
function Intake({ profileForm, setProfileForm, onSubmit }) { const update = (field, value) => setProfileForm(prev => ({ ...prev, [field]: value })); return <><PageTitle eyebrow="AI-ASSISTED INTAKE" title="Tell us about your business" text="A few details are enough to build your first approval map." /><div className="intake-layout"><form className="panel intake-form" onSubmit={onSubmit}><div className="form-section"><span className="section-number">01</span><div><h3>Business identity</h3><p>Use the name that appears on your official documents.</p></div></div><label>Business or project name<input required value={profileForm.name} placeholder="e.g. Priya Foods" onChange={e => update('name', e.target.value)} /></label><label>Industry category<select value={profileForm.industry_category} onChange={e => update('industry_category', e.target.value)}><option value="food_processing">Food processing</option><option value="manufacturing">Manufacturing</option><option value="technology">Technology</option><option value="chemical">Chemical</option></select></label><div className="form-section separated"><span className="section-number">02</span><div><h3>Project details</h3><p>These facts drive the deterministic approval rules.</p></div></div><div className="two-col"><label>District<input required value={profileForm.location_district} onChange={e => update('location_district', e.target.value)} /></label><label>Employees<input type="number" min="0" required value={profileForm.employee_count} onChange={e => update('employee_count', e.target.value)} /></label></div><div className="two-col"><label>Investment (₹)<input type="number" min="0" required value={profileForm.investment_amount} onChange={e => update('investment_amount', e.target.value)} /></label><label>Project stage<select value={profileForm.project_stage} onChange={e => update('project_stage', e.target.value)}><option value="new_setup">New setup</option><option value="expansion">Expansion</option><option value="operating">Operating</option></select></label></div><button className="primary-button full" type="submit"><Sparkles size={17} />Generate my approval map</button></form><div className="intake-aside"><div className="ai-card"><div className="ai-orb"><Sparkles size={20} /></div><span className="eyebrow">YOUR AI GUIDE</span><h3>Plain answers. Clear actions.</h3><p>Gemma reviews what you share, asks when something is unclear, and explains your results in everyday language.</p><div className="quote"><MessageSquareText size={16} />“No guessing. No regulatory jargon.”</div></div><div className="tip"><ShieldCheck size={18} /><div><strong>Rules stay deterministic</strong><p>AI helps with conversation and explanation. Eligibility is always decided by the rules engine.</p></div></div></div></div></> }
function Checklist({ profile, approvals, selectView, onRefresh }) { const items = approvals.length ? approvals : demoApprovals; return <><PageTitle eyebrow="PERSONALISED CHECKLIST" title="Your approval runway" text={profile ? `Built for ${profile.name} · ${profile.location_district}` : 'Load a profile to generate your personalised checklist.'} action={<button className="secondary-button" onClick={onRefresh}><RefreshCw size={15} />Refresh</button>} /><div className="checklist-banner"><div><span className="eyebrow">4 APPROVALS · 2 CAN RUN IN PARALLEL</span><h2>Move with clarity</h2><p>Complete independent approvals together. Dependent steps unlock automatically.</p></div><div className="legend"><span><i className="legend-dot parallel" />Parallel</span><span><i className="legend-dot blocked" />Dependency</span></div></div><div className="checklist-list">{items.map((item, index) => <div className="checklist-card" key={item.approval_id}><div className={`large-step ${index === 0 ? 'active' : ''}`}>{index + 1}</div><div className="checklist-main"><div className="card-top"><div><h3>{item.name}</h3><span>{item.department}</span></div><b className={`status ${index === 0 ? 'in_progress' : 'not_started'}`}>{index === 0 ? 'In progress' : 'Not started'}</b></div><p>{item.applicability_reason}</p><div className="card-foot"><span><FileText size={14} />{item.required_documents.length} documents</span><span><Activity size={14} />{item.sla_days} day SLA</span><span className={item.dependencies.length ? 'dependency' : 'parallel'}>{item.dependencies.length ? 'Unlocks after ' + item.dependencies[0] : 'Can run in parallel'}</span><button className="text-button" onClick={() => selectView('documents')}>Prepare documents <ArrowUpRight size={14} /></button></div></div></div>)}</div></> }
function Documents({ setToast }) { const [file, setFile] = useState(null); const [review, setReview] = useState(null); const [loading, setLoading] = useState(false); async function submit(event) { event.preventDefault(); if (!file) return; setLoading(true); try { const result = await api.reviewDocument(file); setReview(result); setToast('AI review complete') } catch { setReview({ file_name: file.name, status: 'demo_review', score: 78, summary: 'The document is readable, but a few details should be verified before submission.', strengths: ['File type is supported', 'Document appears readable'], issues: ['Signature or official stamp could not be verified'], recommendations: ['Confirm the latest issue date', 'Upload a signed copy if required'], model: 'demo mode', review_id: 'demo-review' }); setToast('Demo review shown. Connect Ollama Cloud for live feedback.') } finally { setLoading(false) } } return <><PageTitle eyebrow="DOCUMENT DESK" title="Prepare with confidence" text="Upload a document and receive constructive pre-validation before handoff." /><div className="document-layout"><form className="panel upload-panel" onSubmit={submit}><div className="upload-zone"><UploadCloud size={29} /><h3>Drop your document here</h3><p>PDF, JPG, or PNG · up to 10 MB</p><input id="doc-upload" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e => setFile(e.target.files[0])} /><label htmlFor="doc-upload" className="secondary-button">Choose file</label>{file && <div className="selected-file"><FileText size={16} /><span>{file.name}</span><button type="button" onClick={() => setFile(null)}><X size={15} /></button></div>}</div><button className="primary-button full" disabled={!file || loading}>{loading ? <><RefreshCw size={16} className="spin" />Reviewing...</> : <><Sparkles size={16} />Review with AI</>}</button></form><div className="panel review-panel">{review ? <><div className="review-score"><div className="score-ring"><strong>{review.score}</strong><span>/100</span></div><div><span className="eyebrow">PRE-VALIDATION RESULT</span><h3>{review.file_name}</h3><p>{review.summary}</p></div></div><ReviewList title="Looks good" items={review.strengths} type="good" /><ReviewList title="Needs attention" items={review.issues} type="issue" /><ReviewList title="Suggested next steps" items={review.recommendations} type="next" /><button className="secondary-button full" onClick={() => setToast('MAITRI handoff is simulated in this MVP')}>Submit to MAITRI <ArrowUpRight size={15} /></button></> : <EmptyState icon={FileCheck2} title="Your review will appear here" text="The AI checks readability, completeness signals, and obvious gaps. It never replaces department scrutiny." />}</div></div></> }
function ReviewList({ title, items, type }) { return <div className="review-list"><h4><span className={`review-dot ${type}`} />{title}</h4>{(items || []).map((item, index) => <p key={index}>{item}</p>)}</div> }
function Schemes({ schemes, filter, setFilter, matches }) { return <><PageTitle eyebrow="SCHEME DIRECTORY" title="Support worth knowing about" text="Explore central and Maharashtra government programmes, all in one place." action={<button className="secondary-button" onClick={() => window.open('https://www.india.gov.in/', '_blank')}><ArrowUpRight size={15} />Official sources</button>} /><div className="scheme-tools"><div className="search-box"><Search size={17} /><input placeholder="Search schemes, benefits, departments..." /></div><div className="segmented"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All schemes</button><button className={filter === 'central' ? 'active' : ''} onClick={() => setFilter('central')}>Central</button><button className={filter === 'state' ? 'active' : ''} onClick={() => setFilter('state')}>Maharashtra</button></div></div><div className="scheme-grid">{schemes.map(scheme => <article className="scheme-card" key={scheme.scheme_id}><div className="scheme-card-top"><span className={`scheme-badge ${scheme.government_level}`}>{scheme.government_level === 'state' ? 'MAHARASHTRA' : 'CENTRAL GOVT'}</span><ArrowUpRight size={17} /></div><h3>{scheme.name}</h3><p>{scheme.description}</p><div className="tag-row">{scheme.tags.map(tag => <span key={tag}>#{tag}</span>)}</div><div className="scheme-divider" /><strong>Key benefits</strong><ul>{scheme.benefits.slice(0, 2).map(item => <li key={item}>{item}</li>)}</ul><a href={scheme.application_url} target="_blank" rel="noreferrer">View application <ArrowUpRight size={14} /></a></article>)}</div><div className="source-note"><ShieldCheck size={16} /><span>Always verify eligibility and deadlines on the official source. Catalogue entries are refreshed periodically.</span></div></> }
function OfficialView({ schemes, onOpenSchemes }) { return <><PageTitle eyebrow="OFFICIAL COMMAND CENTRE" title="A view across the pipeline" text="Monitor applications, service levels, and the places where support can unlock progress." action={<button className="secondary-button" onClick={onOpenSchemes}><BookOpen size={15} />Scheme directory</button>} /><div className="official-metrics"><Stat label="Active applications" value="128" detail="+12 this month" icon={ClipboardCheck} /><Stat label="At SLA risk" value="14" detail="Needs attention" icon={Activity} /><Stat label="Avg. processing" value="18.4d" detail="2.1d faster" icon={RefreshCw} /><Stat label="Incomplete profiles" value="22%" detail="Down from 29%" icon={FileCheck2} /></div><div className="official-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">PIPELINE HEALTH</span><h3>Applications by stage</h3></div><span className="period">Last 30 days</span></div><div className="bars">{[['Submitted', 72], ['In review', 58], ['Query raised', 34], ['Approved', 43]].map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><div><i style={{ width: `${value}%` }} /></div><strong>{value}</strong></div>)}</div></section><section className="panel bottleneck-panel"><div className="panel-heading"><div><span className="eyebrow">BOTTLENECKS</span><h3>Departments to watch</h3></div><Activity size={18} /></div>{[['Pollution Control Board', '6.2d over SLA', 'high'], ['Local Municipal Authority', '2.4d over SLA', 'medium'], ['Fire Department', 'On track', 'good']].map(([name, detail, type]) => <div className="bottleneck" key={name}><span className={`risk-dot ${type}`} /><div><strong>{name}</strong><small>{detail}</small></div><ChevronRight size={15} /></div>)}</section></div><div className="official-note"><Sparkles size={17} /><div><strong>Intelligence layer active</strong><span>Document pre-validation and dependency mapping are reducing avoidable back-and-forth in the simulated pipeline.</span></div></div></> }
function EmptyState({ icon: Icon, title, text }) { return <div className="empty-state"><Icon size={31} /><h3>{title}</h3><p>{text}</p></div> }

export default App
